# Numpy

NumPy, which stands for *"Numerical Python,"* is a popular Python library for numerical and scientific computing. It provides support for working with large, multi-dimensional arrays and matrices of data, along with a collection of mathematical functions to operate on these arrays.

NumPy is a fundamental library for data manipulation and analysis in Python and is widely used in various fields such as data science, machine learning, scientific research, and engineering.

### ndim


It is used to get the dimentions of the array

In [19]:
import numpy as ny

a = ny.array(42)
b = ny.array([1,2,3,4,5])
c = ny.array([[1,2,3],[4,5,6]])

# print(a)
# print(b)
# print(c)

print(a.ndim)
print(b.ndim)
print(c.ndim)


0
1
2


### shape

It is used to get the shape of the array

#### example:

* The array array is a 3-dimensional array with dimensions 2x2x2.
* The shape attribute will return (2, 2, 2).

* This tuple (2, 2, 2) indicates:
   - The first dimension has 2 elements.
   - The second dimension has 2 elements.
   - The third dimension has 2 elements.

In [20]:
import numpy as ny

a = ny.array(42)
b = ny.array([1,2,3,4,5])
c = ny.array([[1,2,3],[4,5,6]])
d = ny.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

# print(a)
# print(b)
# print(c)
# print(d)

print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(2, 2, 3)


In [21]:
import numpy as np
arr=np.array([True,False,True],dtype=np.bool_)
print(arr)
print(arr.dtype)

[ True False  True]
bool


In [22]:
import numpy as np
arr=np.array([1,2.5,'y'],dtype=np.object_)
print(arr)
print(arr.dtype)

[1 2.5 'y']
object


### copy and view


The **copy()** owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.




In [5]:
import numpy as np
arr= np.array([10,20,30,40,50])
arr2=arr[1:4].view()
print(arr)
print(arr2)
arr2[1]=100
print(arr)
print(arr2)


[10 20 30 40 50]
[20 30 40]
[ 10  20 100  40  50]
[ 20 100  40]


The **view()** does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [7]:
import numpy as np
arr= np.array([10,20,30,40,50])
arr2=arr[1:4].copy()
print(arr)
print(arr2)
arr2[1]=100
print(arr)
print(arr2)


[10 20 30 40 50]
[20 30 40]
[10 20 30 40 50]
[ 20 100  40]


In [25]:
import numpy as np
arr=np.zeros((5,3),dtype=np.int_)+9
print(arr)

print("")

arr2=np.ones((5,3),dtype=np.int_)+9
print(arr2)

print("")

arr3=np.eye((3),dtype=np.int_)
print(arr3)

print("")

arr4=np.diag((3,5,7))
print(arr4)

rno = np.random.randint(0,10,8)
print(rno)

print("")

r = np.random.rand(2,3)
print(r)


[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]

[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[3 0 0]
 [0 5 0]
 [0 0 7]]


### **reshape()**

The **reshape()** function allows yo to change the dimensions of the array without changing its data.

This can be useful when you want to rearrange the way data is organized in an array, such as converting a 1-dimensional array into a 2-dimensional matrix or vice versa, or changing the size of a multi-dimensional array while maintaining the total number of elements.

In [27]:
import numpy as np

arr = np.array([10,20,30,40,50,60])
arr1 = arr.reshape(2,-1)
arr2 = arr.reshape(-1,2,1)
arr3 = arr.reshape(2,3)

print(arr1)
print(arr2)
print(arr3)

[[10 20 30]
 [40 50 60]]
[[[10]
  [20]]

 [[30]
  [40]]

 [[50]
  [60]]]
[[10 20 30]
 [40 50 60]]


### **random.seed**

In [29]:
import numpy as np

np.random.seed(1323)
randno = np.random.randint(1,500,30).reshape(5,6)
print(randno)
print(randno[2:,2:])
print(randno[3:5,2:4])

[[336 400 498 411 470 432]
 [495 249  79 207 175 370]
 [392 284  15 250  51 161]
 [477 260 327 322 378 146]
 [348 435 451 258 123 386]]
[[ 15 250  51 161]
 [327 322 378 146]
 [451 258 123 386]]
[[327 322]
 [451 258]]


### **Slicing**

In [30]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9,10])
slicing=arr[4:9]
print(slicing)
print(arr)
print(type(slicing))
print(type(arr))
slicing[:]=0
print(slicing)
print(arr)

[4 5 6 7 8]
[ 0  1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[0 0 0 0 0]
[ 0  1  2  3  0  0  0  0  0  9 10]


# Lab Assignment
(25/07/2024)

In [11]:
#  Hi! I am new to Python numpy. Can you generate some real world situations where I can use a nilimpy array with some source code.

import numpy as np


sample_temperature = np.random.randint(10,60,30)
print(sample_temperature)
threshold = 35

hot_days=np.where(sample_temperature>threshold)
cold_days=np.where(sample_temperature<threshold)

print('Days with index {}  are hot'.format(*hot_days))
print('Days with index {}  are cold'.format(*cold_days))

[35 55 12 26 26 10 25 36 31 53 42 58 28 24 59 15 40 39 24 49 48 57 11 42
 36 58 39 44 35 40]
Days with index [ 1  7  9 10 11 14 16 17 19 20 21 23 24 25 26 27 29]  are hot
Days with index [ 2  3  4  5  6  8 12 13 15 18 22]  are cold


In [10]:
# Hi! Let's create a real-life example involving weather data. Use NumPy to analyze temperature data for a week, 
# perform slicing, indexing, shaping, and reshaping operations, and calculate various statistics.

# Slicing: Extract data for specific days and times.
# Indexing: Access specific temperature values.
# Shaping: Change the shape of the data.
# Reshaping: Reshape the data for different analyses.
import numpy as np

np.random.seed(122)
sample_temperature = np.random.randint(10,60,size=(7,24))
print("Temperature data for a week : ",sample_temperature)

print('Temperature in evening 4pm-7pm each day')


Temperature data for a week :  [[57 36 20 22 26 54 25 44 25 52 31 41 51 16 24 45 46 41 29 23 42 55 30 25]
 [27 21 52 16 58 31 50 33 58 18 19 28 57 31 50 29 41 21 24 38 35 15 23 19]
 [35 55 12 26 26 10 25 36 31 53 42 58 28 24 59 15 40 39 24 49 48 57 11 42]
 [36 58 39 44 35 40 20 29 29 36 16 44 58 44 24 52 35 22 25 34 30 19 30 14]
 [18 54 56 17 28 36 12 54 52 59 14 15 49 51 40 57 37 48 50 47 13 39 59 49]
 [57 59 45 35 13 27 55 52 11 56 30 58 17 11 44 20 34 24 49 56 55 42 51 40]
 [24 44 50 11 11 52 19 59 44 13 27 43 15 57 52 23 27 43 20 48 38 14 43 14]]


### **arange()**

In [3]:
import numpy as np
arr=np.arange(1,8)
print(arr)
print(arr[arr%2==0])
print(arr[arr%2!=0])
print([arr>8])
arr[arr%2==0]=0
print(arr)

arr=np.arange(1,7)
print(arr+2)
print(arr*2)
print(arr**2)



[1 2 3 4 5 6 7]
[2 4 6]
[1 3 5 7]
[array([False, False, False, False, False, False, False])]
[1 0 3 0 5 0 7]
[3 4 5 6 7 8]
[ 2  4  6  8 10 12]
[ 1  4  9 16 25 36]


**min() and max()** is used to return the minmum and maximum value espectively within the array

**argmin() and argmax()** returns the index of minimum and maximum value respectively

In [12]:
import numpy as np
arr=np.array([10,20,30,25,6,2])
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.sqrt(arr))
print(np.sin(arr))
print(np.cos(arr))

2
30
5
2
[3.16227766 4.47213595 5.47722558 5.         2.44948974 1.41421356]
[-0.54402111  0.91294525 -0.98803162 -0.13235175 -0.2794155   0.90929743]
[-0.83907153  0.40808206  0.15425145  0.99120281  0.96017029 -0.41614684]


### **sum() and cumsum()**

In [87]:
import numpy as np
np.random.seed(122)
arr=np.random.randint(1,21,9).reshape(3,3)
print('Original Array : ',arr)
print(np.sum(arr))
print(np.cumsum(arr))
print(np.min(arr))
print(np.max(arr))
print('-------------')
print(np.sum(arr,axis=1))
print(np.min(arr,axis=1))
print(np.max(arr,axis=1))
print(np.cumsum(arr,axis=1))

Original Array :  [[16 11 13]
 [17 13 16]
 [ 3 16 11]]
116
[ 16  27  40  57  70  86  89 105 116]
3
17
-------------
[40 46 30]
[11 13  3]
[16 17 16]
[[16 27 40]
 [17 30 46]
 [ 3 19 30]]


#### Implementation of *cumsum()* using user defined function 

In [21]:
import numpy as np
np.random.seed(122)
arr=np.random.randint(1,21,15).reshape(3,-1)
print(arr)
rows, columns = arr.shape
def custom_cumsum(arr): 
    final=[]
    cumsum=0
    for i in range(rows):
       for j in range(columns):
            cumsum += arr[i][j]
            final.append(cumsum) 
       cumsum=0
    final=np.array(final).reshape(3,-1)
    return(final)

result = custom_cumsum(arr)
print("Custom cumulative sum array:")
print(np.array2string(result, separator=' '))


[[16 11 13 17 13]
 [16  3 16 11 10]
 [ 7 15  4  5 20]]
Custom cumulative sum array:
[[16 27 40 57 70]
 [16 19 35 46 56]
 [ 7 22 26 31 51]]


### **unique()**

In [44]:
import numpy as np
np.random.seed(122)
arr=np.random.randint(1,21,10)
print(arr)
np.random.shuffle(arr)
print(arr)

print(np.unique(arr,return_index=True,return_counts=True))
print(np.unique(arr).size)


[16 11 13 17 13 16  3 16 11 10]
[13 16 16 11 16 10 11 13 17  3]
(array([ 3, 10, 11, 13, 16, 17]), array([9, 5, 3, 0, 1, 8], dtype=int64), array([1, 1, 2, 2, 3, 1], dtype=int64))
6


### **vstack and hstack**

In [52]:
import numpy as np
arr1=np.array([10,20,30,40])
arr2=np.array([50,60,70,80])
print(arr1)
print(arr2)
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

print('-----------------------------')

np.random.seed(122)
arr1=np.random.randint(1,21,9).reshape(3,3)
arr2=np.random.randint(50,80,9).reshape(3,3)
print(arr1)
print(arr2)
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[10 20 30 40]
[50 60 70 80]
[[10 20 30 40]
 [50 60 70 80]]
[10 20 30 40 50 60 70 80]
-----------------------------
[[16 11 13]
 [17 13 16]
 [ 3 16 11]]
[[71 59 56]
 [64 53 54]
 [69 69 63]]
[[16 11 13]
 [17 13 16]
 [ 3 16 11]
 [71 59 56]
 [64 53 54]
 [69 69 63]]
[[16 11 13 71 59 56]
 [17 13 16 64 53 54]
 [ 3 16 11 69 69 63]]


### **searchsorted()**

In [62]:
arr=np.array([10,20,30,40,50,60,70,80,90])
ss=np.searchsorted(arr,90)
print(ss)

8
